# Generated by Django 5.2.4 on 2025-08-21 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('products', '0002_alter_product_seller'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SellerAccount',
        ),
    ]
